src/block.ts, src/block/class.ts, src/block/function.ts, src/block/property.ts, src/completions.ts, src/doc.ts, src/documenter.ts, src/extension.ts
A docblocking extension that isn't properly docblocked. Lets sort that.
=> Fix the irony

src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json, test/functions.test.ts
=> PHP7 return types

src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Make is and has infer return types

src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Support ...$args

src/completions.ts
=> Add lots of doc tags

src/block/function.ts, test/fixtures/classes.php, test/fixtures/classes.php.json, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Namespace issues

package.json, src/block.ts, src/block/function.ts, src/util/TypeUtil.ts, test/TypeUtil.test.ts, test/fixtures/functions.php.json, test/fixtures/properties.php.json
Does it look good? If yes, I make the tests for TypeUtil.ts.
Fixes #34
=> Support customization wether use short or long names

package.json, src/extension.ts
Just adding `hack` as a language appears to work perfectly well. I'm currently using this locally.
=> Added HHVM/Hack support

.travis.yml, src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Fix issue when using a referenced function

package.json, src/doc.ts, src/extension.ts, test/fixtures/doc.json
=> Fix compatibility issues with vscode 1.17.x

src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
For example
`canRead` => true/false
`canLike` => true/false
`canDelete` => true/false
=> Add `can` to the method-prefixes that returns boolean

README.md, package.json, src/doc.ts, test/fixtures/doc.json
=> Allow gap between return and params

README.md
=> Add tags list to README.md

README.md, package.json, src/block.ts, src/block/function.ts, src/completions.ts, src/doc.ts, src/util/TypeUtil.ts, src/util/config.ts, test/TypeUtil.test.ts, test/doc.test.ts, test/fixtures/functions.php.json, test/fixtures/namespace.php, test/functions.test.ts, test/helpers.ts
=> Fully qualify types

src/completions.ts
=> Add description to snippet to avoid confusion

README.md, package.json, src/doc.ts, test/fixtures/doc.json
=> Add option to turn off void return

package.json, src/extension.ts, test/class.test.ts, test/commands.test.ts, test/fixtures/commands.php
This is so you can trigger the command via the command palette.
=> Add command to trigger docblock

CHANGELOG.md
Just a minor typo. 😅
P.S. I love esbuild too. 👏
=> Update a wrong-named dependency

CHANGELOG.md, README.md, package.json, src/block.ts, src/block/class.ts, src/block/function.ts, src/completions.ts
I try to merge the modified parts of my branch into your master.
=> Supported workspace trust

CHANGELOG.md, package.json
Unfortunately no way to guarantee this will work it should help though
=> Make changes to help support vscode web

.gitignore, .vscodeignore, CHANGELOG.md, package-lock.json, package.json, src/util/config.ts, test/doc.test.ts, test/helpers.ts
This allows the extension to work in vscode web!
See #176
=> Remove FS module usage in main code

.github/workflows/release.yml, CHANGELOG.md, package-lock.json, package.json, scripts/updateChangelog.js
Add a GitHub action that performs the following tasks
- Update versions in `package.json` and `package-lock.json`
- Update changelog with version number
- Create tag and release on GitHub with packaged .vsix file
- Publish to marketplace
=> Add script to update change log

CHANGELOG.md, src/block.ts, src/block/function.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Trailing comma

.vscodeignore, CHANGELOG.md, README.md, package-lock.json, package.json, scripts/generateTagTable.ts, scripts/updateChangelog.ts, src/completions.ts, src/tags.ts
It doubles the work of adding a large number of completion tags
**Checks**:
=> Add a script to facilitate adding tags to the README.md

.github/actions/setup/action.yml, .github/workflows/prepare-release.yml, .github/workflows/release.yml, .github/workflows/test.yml, CHANGELOG.md
Makes workflows a little neater
**Checks**:
=> Shared workflow setup

.github/actions/setup/action.yml
Improves speed of test builds
**Checks**:
=> Improve workflow caching

CHANGELOG.md, src/block.ts, test/fixtures/functions.php, test/fixtures/functions.php.json
=> Multi-line trailing comma's

CHANGELOG.md
=> Fix changelog dates

CHANGELOG.md, README.md, package.json, src/doc.ts, test/fixtures/doc.json
So you can add a param description to @var
**Checks**:
=> Add @var description option

package.json
To use newer @types
**Checks**:
=> Update vscode engine to 1.6.0

.github/workflows/test.yml, CHANGELOG.md, package.json, test/index.ts
To try get code coverage more consistent
**Checks**:
=> Add sleep to workflow action

CHANGELOG.md, README.md, package.json, src/block/function.ts, src/block/property.ts, src/util/TypeUtil.ts, test/TypeUtil.test.ts
Allows you to change the default type from `[type]` to anything you want.
Fixes #177 
**Checks**:
=> Allow configuration of default type
